### ISSUE TITLE
npm run dev/npm run article -- -r 报错

### ISSUE THREAD

**Issue by sumh** [leenty/vue2#4]
Node 版本 6.5.0/6.9.2   NPM版本 4.4.4 MacOS
换了两台电脑试，一样的问题，npm install 没有报错

➜  vue2 git:(master) npm install
➜  vue2 git:(master)
---------------------------------------------------------------------------
➜  vue2 git:(master) npm run dev

> vue2.0-demo@1.0.0 dev /Users/mac/vue/vue2
> node build/dev-server.js

Listening at http://localhost:8090

webpack: wait until bundle finished: /index.html
webpack built 8f9293436abdf1b59677 in 6138ms
Hash: 8f9293436abdf1b59677
Version: webpack 1.14.0
Time: 6138ms
 Asset     Size  Chunks       Chunk Names
app.js  2.62 MB       0       app

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-1.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:122-156

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-2.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:260-294

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-3.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:398-432

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-4.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:536-570

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-5.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:674-708

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-6.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:812-846
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0
webpack: Failed to compile.

➜  vue2 git:(master) npm run article -- -r

> vue2.0-demo@1.0.0 article /Users/mac/vue/vue2
> node build/new-article.js "-r"

/Users/mac/vue/vue2/build/create-router.js:14
      resolve(files.filter(v => v.slice(-3) === '.md'))
                   ^

TypeError: Cannot read property 'filter' of undefined
    at /Users/mac/vue/vue2/build/create-router.js:14:20
    at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue2.0-demo@1.0.0 article: `node build/new-article.js "-r"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue2.0-demo@1.0.0 article script 'node build/new-article.js "-r"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue2.0-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/new-article.js "-r"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue2.0-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue2.0-demo
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2017-03-27T09_28_26_462Z-debug.log
➜  vue2 git:(master)

**Comment by leenty** [comment]
哦，sorry，这估计是没有md文件的原因，我没有做没有md文件时的检测，谢谢提供的资料，我已经在这次提交中提供了解决方案
你可以使用`npm run article`系列的命令来解决这个问题了

**Comment by sumh** [comment]
感谢快速响应，clone了最新的repo但是问题还是存在，

执行新命令生成目录，提示目录已经存在了

 ```
node build/new-article.js "-m"
"src/md/articles"目录已存在，无需创建！

```

执行生成新文章的时候提示还是找不到路径
```
> vue2.0-demo@1.0.0 article /Users/mac/vue/vue2
> node build/new-article.js "-n" "test"

找不到文章路径，请使用‘npm run article -- -m’来创建路径
```
生成文章路由的时候依然报错：



```
> node build/new-article.js "-r"

/Users/mac/vue/vue2/build/create-router.js:14
      resolve(files.filter(v => v.slice(-3) === '.md'))
                   ^

TypeError: Cannot read property 'filter' of undefined
    at /Users/mac/vue/vue2/build/create-router.js:14:20
    at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue2.0-demo@1.0.0 article: `node build/new-article.js "-r"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue2.0-demo@1.0.0 article script 'node build/new-article.js "-r"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue2.0-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/new-article.js "-r"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue2.0-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue2.0-demo
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2017-03-29T12_17_01_305Z-debug.log
```


npm run dev无法启动应用

```
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-1.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:122-156

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-2.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:260-294

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-3.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:398-432

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-4.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:536-570

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-5.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:674-708

ERROR in ./src/articlesRoutes.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./md/articles/vue2-6.md in /Users/mac/vue/vue2/src
 @ ./src/articlesRoutes.js 6:812-846
```

应该还是你demo中的现有的几篇文章并没有在repo的中 ，试了一个workaround把utils/articlesRoutes中的原有几篇文章的路由清空现在可以启动应用

```
const articlesRouter = []
export default articlesRouter

```
很喜欢这个界面设计，很清爽。感谢分享以及帮助！

**Comment by leenty** [comment]
嗯，文章放置在`src/md/articles/`下面，所以报错是因为没有找到`articles`这个文件夹引起的

`npm run article -- -m`命令可以创建这个文件夹，但是依你提供的信息里看似已经存在了这个文件夹
但是`npm run article -- -r`又拿不到这个文件夹，你可以进目录看看，是否存在这个文件夹，文件名大小写是否有异常，可以改成`articles`

还有`src/articlesPreRender.js` `src/articleList.json` `src/articlesRoutes.js`这3个文件是可以删除的，使用`npm run article -- -r`可以重新生成他们。
我暂时没有找到问题所在，需要你提供更多信息

还有，多谢关注(～￣▽￣)～

**Comment by sumh** [comment]
你好，我看了下目录，的确是没有生成MD目录，打印了一下err
├── src
│   ├── App.vue
│   ├── App1.vue
│   ├── articleList.json
│   ├── articlesPreRender.js
│   ├── articlesRoutes.js
│   ├── assets
│   ├── components
│   ├── main.js
│   ├── resources.js
│   ├── router.js
│   ├── routes.js
│   ├── services
│   ├── store
│   └── utils

```
> vue2.0-demo@1.0.0 article /Users/mac/vue/vue2
> node build/new-article.js "-m"

"src/md/articles"目录已存在，无需创建！

 { Error: ENOENT: no such file or directory, mkdir '/Users/mac/vue/vue2/src/md/articles'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/Users/mac/vue/vue2/src/md/articles' }
Usage: npm run article -- [[-m] | [-n 'fileName'] | [-r] | [-h]]
or: node build/new-article.js [[-n 'fileName'] | [-r] | [-h]]
```

应该是因为父目录md和子目录articles 都不存在Node的fs.mkdir不能同时创建父子目录，找了一个mkdirp 

https://github.com/substack/node-mkdirp/

```
const mkDir = function () {
  mkdirp(path.join(__dirname,'../src/md/articles'), function (err, files) {
    if (err) {
      console.log('"src/md/articles"目录已存在，无需创建！\n\n',err)
    } else {
      console.log('"src/md/articles"目录创建成功！\n\n')
    }
    showHelp()
  })
}
```
```

➜  vue2 git:(master) ✗ npm run article -- -m

> vue2.0-demo@1.0.0 article /Users/mac/vue/vue2
> node build/new-article.js "-m"

"src/md/articles"目录创建成功！

```
现在npm run article -- n 已经ok了，npm run dev 也能看到新加入的文章页面，问题应该解决了，多谢

**Comment by leenty** [comment]
ok,我重写了部分代码，把`npm run article -- -m`命令移除了
在`npm run article -- -n 'fileName'`的时候会自动创建那个目录
使用了[https://github.com/substack/node-mkdirp/](https://github.com/substack/node-mkdirp/)这个库。
详细可以看[这条提交c6f0512](https://github.com/leenty/vue2/commit/c6f0512)

**Comment by sumh** [comment]
感谢效率支持，测试了一下新的release还是有一些问题

```
➜  vue2 git:(master) ✗ npm run article -- -n "test"

> vue2.0-demo@1.0.0 article /Users/mac/vue/vue2
> node build/new-article.js "-n" "test"

/Users/mac/vue/vue2/build/new-article.js:73
async function createArticle(arg) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue2.0-demo@1.0.0 article: `node build/new-article.js "-n" "test"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue2.0-demo@1.0.0 article script 'node build/new-article.js "-n" "test"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue2.0-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/new-article.js "-n" "test"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue2.0-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue2.0-demo
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2017-03-31T04_27_53_756Z-debug.log
```

应该是我的node版本还不支持新的async/await功能，查了下node对async/await的支持好像在7.6以后，升级到目前的stable node 7.8.0后ok，建议在readme前面说明一下版本要求，毕竟node 6还有一些用户在用以免使用的时候造成consfused。或者用一些第三方的异步处理库代替。感谢！

**Comment by leenty** [comment]
哈哈哈，这个。。是我作死了，突然用了下async函数,尴尬😅，我已经更新了README
多谢支持٩(^ω^)۶
